name: Release CI

on:
  workflow_dispatch:
  push:
    tags:
      - v**

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    if: startsWith(github.repository, 'qiuyeyijian')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (ubuntu only)
        if: startsWith(matrix.platform, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf openssl

      - name: Install frontend dependencies
        run: |
          pnpm install

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        # enable cache even though failed
        # continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: "EMDev v__VERSION__"
          releaseBody: "More new features are now supported."
          releaseDraft: false
          prerelease: true
          includeDebug: false

      - name: Portable Bundle
        if: startsWith(matrix.platform, 'windows-')
        # rebuild with env settings
        run: |
          pnpm build
          pnpm run portable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          VITE_WIN_PORTABLE: 1

  release-update:
    needs: release
    runs-on: ubuntu-latest
    if: |
      startsWith(github.repository, 'qiuyeyijian') &&
      startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Pnpm install
        run: pnpm install

      - name: Release updater file
        run: pnpm run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
