name: Updater CI

on: workflow_dispatch

jobs:
  release-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Pnpm install
        run: pnpm install

      - name: Release updater file
        run: pnpm run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
