name: Updater CI

on: workflow_dispatch

jobs:
  release-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Release updater file
        run: |
          pnpm install
          pnpm run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
